//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRAINER
    {
        public int ID { get; set; }
        public string NAME { get; set; }
        public string FIRSTNAME { get; set; }
        public string PROMOTIONFUT { get; set; }
        public string PROMOTIONCUR { get; set; }
        public string EMAIL { get; set; }
        public string CAMPUS { get; set; }
        public string COURSESWT { get; set; }
        public string COURSESAT { get; set; }
        public string CAMPUSAC { get; set; }
        public string CAMPUSWC { get; set; }
        public string DIVERSCERTIF { get; set; }
        public string COMMENTS { get; set; }
    }
}
