//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tripping_octo_nemesis
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notation
    {
        public int Notation_Id { get; set; }
    }
}
