//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tripping_octo_nemesis
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teacher
    {
        public int Teacher_Id { get; set; }
        public string Name { get; set; }
        public string Firstname { get; set; }
        public string PromValid { get; set; }
        public string PromCurrent { get; set; }
        public string Email { get; set; }
        public string Campus { get; set; }
        public string CourseCurrent { get; set; }
        public string CourseFutur { get; set; }
        public string CampusCurrent { get; set; }
        public string CampusFutur { get; set; }
    }
}
